# y dataset pipeline

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))

from data_loaders import Training_set
import pandas as pd
import numpy as np

In [5]:
ts = Training_set()
x_train, y_train, _, _= ts.split_small_data()
y_train.head()

,run_no,total_calculation_time,result_committed_hogga_g1_t0,result_committed_hogga_g1_t1,result_committed_hogga_g1_t2,result_committed_hogga_g1_t3,result_committed_hogga_g1_t4,result_committed_hogga_g1_t5,result_committed_hogga_g1_t6,result_committed_hogga_g1_t7,...,result_committed_vesle_kjela_g1_t158,result_committed_vesle_kjela_g1_t159,result_committed_vesle_kjela_g1_t160,result_committed_vesle_kjela_g1_t161,result_committed_vesle_kjela_g1_t162,result_committed_vesle_kjela_g1_t163,result_committed_vesle_kjela_g1_t164,result_committed_vesle_kjela_g1_t165,result_committed_vesle_kjela_g1_t166,result_committed_vesle_kjela_g1_t167
starttime,,,,,,,,,,,,,,,,,,,,,
2015-01-01 00:00:00+00:00,1,48.950692,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-02 00:00:00+00:00,2,56.048899,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-03 00:00:00+00:00,3,44.280307,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-04 00:00:00+00:00,4,40.848453,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-05 00:00:00+00:00,5,44.036279,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [6]:
y_train.tail()

,run_no,total_calculation_time,result_committed_hogga_g1_t0,result_committed_hogga_g1_t1,result_committed_hogga_g1_t2,result_committed_hogga_g1_t3,result_committed_hogga_g1_t4,result_committed_hogga_g1_t5,result_committed_hogga_g1_t6,result_committed_hogga_g1_t7,...,result_committed_vesle_kjela_g1_t158,result_committed_vesle_kjela_g1_t159,result_committed_vesle_kjela_g1_t160,result_committed_vesle_kjela_g1_t161,result_committed_vesle_kjela_g1_t162,result_committed_vesle_kjela_g1_t163,result_committed_vesle_kjela_g1_t164,result_committed_vesle_kjela_g1_t165,result_committed_vesle_kjela_g1_t166,result_committed_vesle_kjela_g1_t167
starttime,,,,,,,,,,,,,,,,,,,,,
2018-12-27 00:00:00+00:00,1457,36.421398,0,0,0,0,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
2018-12-28 00:00:00+00:00,1458,36.417097,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2018-12-29 00:00:00+00:00,1459,34.065280,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2018-12-30 00:00:00+00:00,1460,36.166081,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2018-12-31 00:00:00+00:00,1461,34.137959,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0